FROM    alpine:3.15.1 AS build

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    helloworld.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
            --descriptor_set_out=helloworld.pb helloworld.proto

FROM    envoyproxy/envoy:v1.21.1

COPY    --from=build /app/helloworld.pb /tmp/
